var skillTrees = {
    // Combat Classes
    "Archer":[
        "Deadly Accuracy",
        "Deadly Accuracy",
        "Focused Strike: Agility",
        "Grit",
        "Point Blank",
        "Rapid Reaction",
        "Barrage",
        "Brace",
        "Precise Aim",
        "Second Wind",
        "Rapid Recovery",
        "Barrage",
        "Precise Aim",
        "Deadeye",
        "Crack Shot",
        "Natural Archer",
        "Crippling Blow",
        "Dedication",
        "Specialty Arrows",
        "True Aim"
    ],

    "Assassin":[
        "Quick Strike",
        "Indistinguishable",
        "Focused Strike: Cunning",
        "Quick Strike",
        "Rapid Reaction",
        "Swift",
        "Quick Draw",
        "Skill Proficiency: Skulduggery",
        "Skill Mastery: Stealth",
        "Lethal Blows",
        "Rapid Reaction",
        "Lethal Blows",
        "Superior Reflexes",
        "Intense Focus",
        "Natural Rogue",
        "Dodge",
        "Stalker",
        "Dedication",
        "Assassination",
        "Crippling Blow"
    ],

    "Barbarian":[
        "Focused Strike: Brawn",
        "Knockdown",
        "Deadly Accuracy",
        "Grit",
        "Toughened",
        "Toughened",
        "Swift",
        "Durable",
        "Relentless",
        "Creative Killer",
        "Skill Mastery: Coercion",
        "Hard Headed",
        "Feral Strength",
        "Feral Strength",
        "Frenzied Attack",
        "Frenzied Attack",
        "Dedication",
        "Indomitable Rage",
        "Cleave",
        "Steely Resolve"
    ],

    "Duelist":[
        "Grit",
        "Scuttlebutt",
        "Grit",
        "Focused Strike: Dueling",
        "Deft Defense",
        "Second Wind",
        "Disarming",
        "Grit",
        "Alert",
        "Deft Defense",
        "Precise Aim",
        "Second Wind",
        "Sociologist",
        "Superior Reflexes",
        "Dodge",
        "Defensive Dueling",
        "Genteel",
        "Riposte",
        "Dedication",
        "Single Combat"
    ],

    "Soldier":[
        "Focused Strike: Brawn",
        "Grit",
        "Grit",
        "Knockdown",
        "Toughened",
        "Durable",
        "Toughened",
        "Confidence",
        "Swift",
        "Hard Headed",
        "Rapid Recovery",
        "Second Wind",
        "Shield Master",
        "Feral Strength",
        "Natural Soldier",
        "Armor Master",
        "Heroic Fortitude",
        "Dedication",
        "Executioner",
        "Action Surge"
    ],

    // Utility Classes
    "Beastmaster":[
        "Forager",
        "Outdoorsman",
        "Focused Strike: Agility",
        "Expert Tracker",
        "Skill Proficiency: Animal Handling",
        "Animal Tamer",
        "Hunter",
        "Horsemanship",
        "Combat Conditioning",
        "Animal Synergy",
        "Rapid Recovery",
        "Skill Mastery: Animal Handling",
        "Faunologist",
        "Rapid Reaction",
        "Animal Tamer (Improved)",
        "Sixth Sense",
        "Exotic Mount",
        "On the Hunt",
        "Exotic Pet",
        "Dedication"
    ],

    "Field Medic":[
        "Grit",
        "Forager",
        "Touch of Fate",
        "Skill Proficiency: Medicine",
        "Medical Kit Expert",
        "Swift",
        "Medical Kit Expert",
        "Medical Kit Expert",
        "Skill Mastery: Medicine",
        "Bodyguard",
        "Medicinal Stimulants",
        "Medicinal Stimulants (Improved)",
        "Dodge",
        "Natural Medic",
        "It's Not That Bad",
        "Homeopathy",
        "Intense Focus",
        "Dedication",
        "Surgeon",
        "Superior Reflexes"
    ],

    "Inquisitor":[
        "Expert Tracker",
        "Quick Draw",
        "Grit",
        "Focused Strike: Cunning",
        "Blackmail",
        "Confidence",
        "Well Rounded",
        "Blackmail",
        "Greased Palms",
        "Rapid Reaction",
        "Skill Mastery: Coercion",
        "Group Awareness",
        "Armor Master",
        "Sociologist",
        "Challenging Shout",
        "Smooth Talker",
        "Fearsome Reputation",
        "Dedication",
        "Challenging Shout (Improved)",
        "Intense Focus"
    ],

    "Monster Hunter":[
        "Extrasensory Perception",
        "Arcane Predation",
        "Expert Tracker",
        "Outdoorsman",
        "Utility Belt",
        "Toughened",
        "Well Rounded",
        "Grit",
        "Touch of Undeath",
        "Silver Inlay",
        "Toughened",
        "Swift",
        "Preternatural Senses",
        "Arcanologist",
        "Faunologist",
        "Dodge",
        "Indignance",
        "Dedication",
        "Knowing is Half the Battle",
        "Big Game Hunter"
    ],

    "Ranger":[
        "Outdoorsman",
        "Forager",
        "Expert Tracker",
        "Focused Strike: Agility",
        "Horsemanship",
        "Skill Proficiency: Animal Handling",
        "Hunter",
        "Hunter",
        "Skill Mastery: Survival",
        "Skill Mastery: Animal Handling",
        "Barrage",
        "Rapid Reaction",
        "Group Awareness",
        "Natural Ranger",
        "Sixth Sense",
        "Deadeye",
        "Armor Master",
        "Stalker",
        "Dance of Blades",
        "Dedication"
    ],
    
    // Innate Classes
    "Channeler":[
        "Grit",
        "Focused Strike: Willpower",
        "Spellcasting: Natural",
        "Quick Draw",
        "Toughened",
        "Grit",
        "Swift",
        "Grit",
        "Numbed Senses",
        "Toughened",
        "Spellcasting: Developed",
        "Swift",
        "Imbue Element",
        "Armor Master",
        "War Caster",
        "Natural Channeler",
        "Dedication",
        "Overdraw",
        "Mastered Spell: Elemental Nova",
        "Elemental Attunement"
    ],

    "Druid":[
        "Forager",
        "Outdoorsman",
        "Spellcasting: Natural",
        "Outdoorsman",
        "Skill Proficiency: Innate",
        "Skill Proficiency: Survival",
        "Grit",
        "Grit",
        "Recluse",
        "Wild Empathy",
        "Spellcasting: Developed",
        "Woodland Stride",
        "Natural Trainer",
        "One with the Magicks",
        "Lay of the Land",
        "Faunologist",
        "Unarmored Mastery",
        "Dedication",
        "Mastered Spell: Control Terrain",
        "Strength of the Wild"
    ],

    "Shapeshifter":[
        "Skill Proficiency: Survival",
        "Outdoorsman",
        "Forager",
        "Spellcasting: Natural",
        "Stunning Blows",
        "Hunter",
        "Spirit Animal",
        "Toughened",
        "Stunning Blows (Improved)",
        "Spellcasting: Developed",
        "Toughened",
        "Feral Strength",
        "Feral Strength",
        "Natural Beast",
        "Spirit Animal (Improved)",
        "Sixth Sense",
        "Superior Reflexes",
        "Dedication",
        "Spirit Transformation",
        "Unarmored Mastery"
    ],

    "Sage":[
        "Grit",
        "Spellcasting: Natural",
        "Touch of Fate",
        "Grit",
        "Smooth Talker",
        "Song of Rest",
        "Skill Proficiency: Innate",
        "Slippery Minded",
        "Nobody's Fool",
        "Spellcasting: Developed",
        "Representative",
        "Inspiring Rhetoric",
        "Ritual Transference",
        "Natural Wiseman",
        "Inspiring Rhetoric (Supreme)",
        "Inspiring Rhetoric (Improved)",
        "Historical Illumination",
        "Mastered Spell: Divination",
        "Dedication",
        "Insightful Ancestors"
    ],

    "Fundamentalist":[
        "Grit",
        "Lawful Manipulation",
        "Grit",
        "Skill Proficiency: Innate",
        "Well Rounded",
        "Rapid Reaction",
        "Grit",
        "Swift",
        "Mass Modulation",
        "Rapid Recovery",
        "Theoretical Manipulation",
        "Temperature Modulation",
        "Restoring Force",
        "Gravity Modulation",
        "Extradimensional Storage",
        "Light Modulation",
        "Equilibrium",
        "Dedication",
        "Hypothetical Spell",
        "Temperature Modulation (Improved)"
    ],

    // Scholarly Classes
    "Bard":[
        "In the Know",
        "Spellcasting: Initiate",
        "Grit",
        "Skill Proficiency: Performance",
        "Spellcasting: Adept",
        "Encouraging Words",
        "Song of Rest",
        "Smooth Talker",
        "Well Rounded",
        "Spellcasting: Magister",
        "Second Wind",
        "Bardic Inspiration",
        "Magical Performer",
        "Nobody's Fool",
        "Natural Performer",
        "Spellcasting: Arcanist",
        "Dedication",
        "Jack of All Trades",
        "Spellmaster",
        "Practical Experience"
    ],

    "Battlemage":[
        "Skill Proficiency: Scholarly Magic",
        "Grit",
        "Spellcasting: Initiate",
        "Grit",
        "Spellcasting: Adept",
        "Rapid Reaction",
        "Toughened",
        "Well Rounded",
        "Second Wind",
        "Rapid Recovery",
        "Arcane Potency",
        "Spellcasting: Magister",
        "Superior Reflexes",
        "Spellcasting: Arcanist",
        "Magical Acceleration",
        "Sixth Sense",
        "Martial Arcana",
        "Dedication",
        "Spell Penetration",
        "Armor Master"
    ],

    "Necromancer":[
        "Grit",
        "Spellcasting: Initiate",
        "Skill Proficiency: Scholarly Magic",
        "Grit",
        "Disease Immunity",
        "Grit",
        "Confidence",
        "Spellcasting: Adept",
        "Touch of Undeath",
        "Rapid Recovery",
        "Spellcasting: Magister",
        "Toughened",
        "Spellcasting: Arcanist",
        "Death's Friend",
        "Summoner",
        "Power of the Grave",
        "Consume the Enslaved",
        "Blood of the Master",
        "Summoner",
        "Dedication"
    ],

    "Researcher":[
        "Spellcasting: Initiate",
        "Grit",
        "Skill Proficiency: Knowledge Skill",
        "Grit",
        "Slippery Minded",
        "Spellcasting: Adept",
        "Well Rounded",
        "Well Read",
        "Stroke of Intellect",
        "Living Encyclopedia",
        "Spellcasting: Magister",
        "Skill Mastery: Knowledge Skill",
        "Arcanologist",
        "Thorough Assessment",
        "Arcane Scholar",
        "Spellcasting: Arcanist",
        "Spellmaster",
        "Dedication",
        "Epiphany",
        "Spell Index"
    ],

    "Wizard":[
        "Spellcasting: Initiate",
        "Skill Proficiency: Scholarly Magic",
        "Metamagician",
        "Grit",
        "Slippery Minded",
        "Grit",
        "Spellcasting: Adept",
        "Grit",
        "Magical Duelist",
        "Expertise",
        "Arcane Potency",
        "Spellcasting: Magister",
        "Alert",
        "Spell Efficiency",
        "Spellcasting: Arcanist",
        "Metamagic Master",
        "Dedication",
        "Complex Caster",
        "Spellmaster",
        "Perfectionist"
    ],

    // Speech Classes
    "Charlatan":[
        "Scuttlebutt",
        "Focused Strike: Cunning",
        "Supporting Evidence",
        "Skill Proficiency: Deception",
        "Indistinguishable",
        "Skill Proficiency: Charm",
        "Hidden Storage",
        "Quick Strike",
        "Expertise",
        "Skill Mastery: Society",
        "Smooth Talker",
        "Nobody's Fool",
        "Genteel",
        "Smooth Talker",
        "Sociologist",
        "Deceptive Strike",
        "Unarmored Mastery",
        "Dedication",
        "Power Play",
        "Superior Reflexes"
    ],
    
    "Commander":[
        "Skill Proficiency: Leadership",
        "Focused Strike: Presence",
        "Grit",
        "Focused Strike: Allies",
        "Confidence",
        "Rapid Reaction",
        "Toughened",
        "Well Rounded",
        "Inspiring Rhetoric (Improved)",
        "Inspiring Rhetoric",
        "Coordinated Assault",
        "Coordinated Assault",
        "Inspiring Rhetoric (Supreme)",
        "Warcry",
        "Team Player",
        "Field Commander",
        "Armor Master",
        "Battle Plan",
        "Dedication",
        "Field Commander (Improved)"
    ],

    "Drunken Master":[
        "Indistinguishable",
        "Alcoholic",
        "Skill Proficiency: Deception",
        "Indistinguishable",
        "Toughened",
        "Quick Strike",
        "Stunning Blows",
        "Tavern Brawler",
        "Numbed Senses",
        "Slippery Minded",
        "Stunning Blows (Improved)",
        "Creative Killer",
        "Discredit",
        "Hold Your Liquor",
        "Dodge",
        "Deceptive Strike",
        "Dedication",
        "Superior Reflexes",
        "Foot in the Door",
        "Unarmored Mastery"
    ],

    "Merchant":[
        "Supporting Evidence",
        "Wheel and Deal",
        "Skill Proficiency: Negotiation",
        "Wheel and Deal",
        "Utility Belt",
        "Smooth Talker",
        "In the Know",
        "Street Vendor",
        "Nobody's Fool",
        "Well Rounded",
        "Greased Palms",
        "Wheel and Deal",
        "De-escalation Technique",
        "Nobody's Fool",
        "Dodge",
        "Smooth Talker",
        "Aggressive Negotiations",
        "Rare Weapon",
        "Dedication",
        "Traveling Merchant"
    ],

    "Performer":[
        "In the Know",
        "Grit",
        "Quick Draw",
        "Skill Proficiency: Performance",
        "Deft Defense",
        "Encouraging Words",
        "Song of Rest",
        "Well Rounded",
        "Expertise",
        "Second Wind",
        "Deft Defense",
        "Second Wind",
        "Superior Reflexes",
        "Entertainer's Dexterity",
        "Smooth Talker",
        "Smooth Talker",
        "Unarmored Mastery",
        "Dedication",
        "Distraction",
        "Distraction (Improved)"
    ]
}

export default skillTrees;